package com.opensource.cybercitizen.activity.model;


public class DTSBus
{
    private String station;
    private String locationHint;
    private double latitude;
    private double longitude;

    private static class Dataset
    {
        private static final String[] streetName = "CYBERJAYA LAKE CARDEN,CYBERJAYA LAKE CARDEN,D'PULZE CYBERJAYA,D'PULZE CYBERJAYA,CYBER 5,CYBER 5,GLOMAC CYBERJAYA (BARAT),GLOMAC CYBERJAYA (BARAT),WISMA SHELL,WISMA SHELL,QUILL 4 CYBERJAYA,QUILL 4 CYBERJAYA,GLOMAC CYBERJAYA (TIMUR),GLOMAC CYBERJAYA (TIMUR),LIM KOK WING UNIVERSITY (TIMUR),LIM KOK WING UNIVERSITY (TIMUR),LIM KOK WING UNIVERSITY (BARAT),LIM KOK WING UNIVERSITY (BARAT),ZON TEKNOLOGI MKN EMBASSY,ZON TEKNOLOGI MKN EMBASSY,MULTIMEDIA DEVELOPMENT CORPORATION (MDEC),MULTIMEDIA DEVELOPMENT CORPORATION (MDEC),CENTURY SQUARE,CENTURY SQUARE,SHAFTSBURY SQUARE,SHAFTSBURY SQUARE,CYBERVIEW GARDEN VILLAS,CYBERVIEW GARDEN VILLAS,PERDANA LAKEVIEW EAST,PERDANA LAKEVIEW EAST,PERDANA LAKEVIEW WEST,PERDANA LAKEVIEW WEST,SEK SERI PUTERI CYBERJAYA,SEK SERI PUTERI CYBERJAYA,CYBER SPORTS ARENA,CYBER SPORTS ARENA,PRIMA AVENUE 1,PRIMA AVENUE 1,UNIVERSITI MALAYSIA OF COMPUTER SCIENCE AND ENGINEERING,UNIVERSITI MALAYSIA OF COMPUTER SCIENCE AND ENGINEERING,MAGIC CENTER,MAGIC CENTER,KOMPLEKS BALAI POLIS CYBER,KOMPLEKS BALAI POLIS CYBER,BALAI BOMBA CYBER,BALAI BOMBA CYBER,MENARA HASIL CYBER (UTARA),MENARA HASIL CYBER (UTARA),MENARA HASIL CYBER (BARAT),MENARA HASIL CYBER (BARAT),THE DOMAIN NEOCYBER (TIMUR),THE DOMAIN NEOCYBER (SELATAN),THE DOMAIN NEOCYBER (SELATAN),CYBERIA CRESCENT 2,CYBERIA CRESCENT 2,MIGHT CYBERJAYA,MIGHT CYBERJAYA,CYBERJAYA TRANSPORT TERMINAL,MMU CYBERJAYA,MMU CYBERJAYA,CYBERIA CRESCENT CONDOMINIUM,CYBERIA CRESCENT CONDOMINIUM,CYBERJAYA SMART SCHOOL COMPLEX,CYBERJAYA SMART SCHOOL COMPLEX,THE ARC CYBERJAYA ,THE ARC CYBERJAYA ,MMU CYBERJAYA ,NO_NAME,NO_NAME".split(",");

        private static final String[] locationHint = "Hadapan MMU,Bertentangan MMU,Hadapan D'Puzle Cyberjaya,Hadapan Cyberjaya Transport Terminal,Hadapan HSBC,Hadapan BMW Showroom,Hadapan Quill 18,Hadapan Glomac Cyberjaya,Hadapan Wisma Shell,Bertentangan Wisma Shell,Hadapan Innovation Centre,Hadapan DHL Cyber,Hadapan Glomac Cyberjaya,Bertentangan Glomac Cyberjaya,Hadapan Lim Kok Wing University,Bertentangan Lim Kok Wing University,Hadapan Lim Kok Wing University,Bertentangan Lim Kok Wing University,Bertentangan MKN Embassy Techzone,Hadapan MKN Embassy Techzone,Bertentangan MSC HQ,Hadapan MSC HQ,Bertentangan Shaftsbury Square,Hadapan Shaftsbury Square,Bertentangan Shaftsbury King Bakery,Hadapan King Bakery,Hadapan Multimedia Super Coridor,Hadapan Cyber View Garden,Hadapan Perdana Lake View East,Bertentangan Perdana Lake View East  ,Bertentangan Perdana Lake View West ,Hadapan Perdana Lake View West ,Hadapan Cyber Height Villa,Hadapan Sekolah Seri Puteri,Hadapan Cyber Sport Arena,Bertentangan Cyber Sport Arena,Hadapan Prima Avenue 1,Hadapan Prima Avenue 1,Bertentangan Wisma Avis ,Hadapan Axis Enreka ,Hadapan Wisma Dell,Hadapan Magic ,Hadapan Basic Bay,Hadapan Kompleks Balai Polis Cyber,Hadapan Balai Bomba Cyber,Hadapan Wisma Dell,Hadapan LHDN Cyber,Bertentangan LHDN Cyber,Hadapan LHDN Cyber,Hadapan Wisma HP,Hadapan The Domain Cyber,Hadapan Wisma Mustapha Kamal,Hadapan CSF Cmputer Data Centre ,Hadapan Cyberia Crescent 2,Hadapan D'Melur Condo,Bertentangan MIGHT,Hadapan MIGHT,Hentian Bas Cyberjaya,Hadapan Cyberjaya Crescent Kondo,Bertentangan Cyberia Crescent Kondo,Hadapan SK Cyberjaya 1,Bertentangan SK Cyberjaya 1,Hadapan SMK Cyberjaya ,Bertentangan SMK Cyberjaya ,Hadapan The ARC Cyberjaya,Hadapan Cyberia Kondo,Hadapan MMU,Hadapan PMU Air Hitam ,Hadapan Laman Bayu".split(",");
    }
}
